### PR TITLE
Merged branch master -> exist-3.4.1-compatibility 

### PR DESCRIPTION
**Pull request by plutonik-a**

### CODE REVIEW

**Comment by joewiz** [comment]
This updates the 3.4.1 compatibility branch with commits to master that hadn’t been merged into the former, correct? Does it preserve the commits needed to ensure 3.4.1 compatibility? (Also, I don’t think we’ll be needing this branch much longer - I expect we’ll upgrade to 4.0.0 within a week or two, as we discussed on Wednesday.)

**Comment by plutonik-a** [comment]
@joewiz Unfortunately, 4 commits from a build enhancement slipped into this PR, which were meant to be published separately. If you don't mind, I'll leave them here and delete the duplicate PR https://github.com/HistoryAtState/hsg-shell/pull/330.

**Comment by plutonik-a** [comment]
@joewiz //cc @tuurma 
> This updates the 3.4.1 compatibility branch with commits to master that hadn’t been merged into the former, correct? 

Yes.

> Does it preserve the commits needed to ensure 3.4.1 compatibility?

I reviewed both branches with diff and I can confirm, that both the relevant fixes were preserved in `merged-master-branch`.  
The only significant difference was the use of arrow functions in `search.xqm` (https://github.com/HistoryAtState/hsg-shell/blob/master/modules/search.xqm) which is incompatible with exist 3.4.1, so I reverted it to the version of branch exist-3.4.1-compatibility (https://github.com/HistoryAtState/hsg-shell/blob/exist-3.4.1-compatibility/modules/search.xqm).

> I don’t think we’ll be needing this branch much longer - I expect we’ll upgrade to 4.0.0 within a week or two

Ok, my point is just to consolidate all active branches into one dev and one stable branch in the end and we can rename them after merging the open PRs.

**Comment by joewiz** [comment]
I didn't mean to summarily close the PR just now, but I did delete the exist-3.4.1-compatibility branch after simply committing a backward compatible version of search.xqm to master. See my comments at https://github.com/HistoryAtState/hsg-shell/commit/26a10e7c65f4ed2bc458759918c3d95cca067f5a. I'll review your build enhancement commits this afternoon and merge those in too.

**Pull request closed without merging**
