### PR TITLE
Implement COM "arrived" structure

### PR DESCRIPTION
**Pull request by joewiz**
See https://github.com/HistoryAtState/pocom/issues/29

@joshbotts If you send me the text to be added to ["Dates of Service"](https://history.state.gov/departmenthistory/people/principals-chiefs#dates-of-service) on the POCOM landing page, I can fold it into the [the HTML template](https://github.com/HistoryAtState/hsg-shell/blob/master/pages/departmenthistory/people/principals-chiefs.xml) and include it in this PR.

## Individual country chief

e.g., http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/popp-william-w

**Before**

> Screen Shot 2022-02-05 at 11 39 40 AM

**After**

> Screen Shot 2022-02-05 at 11 40 03 AM

## Chiefs to country

e.g., http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/chiefsofmission/brazil

**Before**

> Screen Shot 2022-02-05 at 12 11 00 PM

**After**

> Screen Shot 2022-02-05 at 12 11 12 PM

## Chiefs to IO

e.g., http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/lapenn-jessica

**Before**

> Screen Shot 2022-02-05 at 12 21 05 PM

**After**

> Screen Shot 2022-02-05 at 12 21 12 PM

### CODE REVIEW

**Comment by joshbotts** [comment]
HI @joewiz - This looks great! The updated text for the landing page is here: https://github.com/HistoryAtState/pocom/issues/29#issuecomment-1035426028

Thanks!

**Review by joshbotts — COMMENTED** [review]
Did you intend to capitalize Chief of Mission in "Both assumption of charge over the U.S. mission and presentation of credentials to the host government are important elements of a chief of mission’s entrance on duty"?

**Review by joshbotts — COMMENTED** [review]
Looks good!

**Comment by joewiz** [comment]
@joshbotts Indeed, I did intend to! Thanks for spotting that!

**Pull request merged**
