### PR TITLE
Reorganize menu bar, retire milestones

### PR DESCRIPTION
**Pull request by joewiz**
Closes https://github.com/HistoryAtState/hsg-shell/issues/276

### CODE REVIEW

**Comment by joewiz** [comment]
Menu bar showing change in "About Us" and "Milestones":

> screen_shot_2017-04-14_at_4_56_59_pm

**Comment by joewiz** [comment]
Here's my initial take at Milestones deprecation status:

> screen_shot_2017-04-14_at_4_59_02_pm

For discussion:

- Is the text clear? Does it answer the questions that readers might have?
- Does the styling of the text reflect the intent of this notice? 

@plutonik-a Could you suggest any improvements in the styling of this notice? I'm just using the bootstrap alert class from http://getbootstrap.com/components/#alerts.

Once we settle on text/messaging and styling, I can apply this to the sub-pages within the section.

**Comment by awmarrs** [comment]
Joe, you might want to check with Tiffany, but I think we get a lot of questions asking us when this was written -- people's teachers are making them include that in their citations. We always tell them 2009, I think. Perhaps "This publication (written in 2009) is no longer maintained" might alleviate some of that. Thanks for getting this process started!

**Comment by joewiz** [comment]
@awmarrs Good idea! I'll do that - and mentioned this to Bill too.

**Pull request merged**
